### ISSUE TITLE
Facebook Share Button not working

### ISSUE THREAD

**Issue by gastelumstudio** [social9/bug-tracker#1]
Hi,

I keep getting this error when I hit the Facebook Share button:
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

I wonder if the app is public yet.

**Comment by cnp96** [comment]
Hi @gastelumstudio,

Thanks for bringing this to our attention. 

I've again verified that our Facebook app is currently live.

It looks like Facebook is blocking any content being shared from the **9sh.re** or **ish.re** domain. I've contacted Facebook support regarding the same and yet to receive a reply.

**Comment by cnp96** [comment]
We've temporarily updated the domain until a resolution is received from Facebook support. The service should be working now.

Again, thanks for bringing this into our attention 👍
