### ISSUE TITLE
Same issue with double loading icons

### ISSUE THREAD

**Issue by jessicaoddi** [social9/bug-tracker#12]
https://www.pauseandeffect.ca/resources/why-we-need-to-change-our-company-name

**Comment by kunal-saini** [comment]
Hey @jessicaoddi 

Thank you for reporting the issue! Could you please provide us with more details on the issue? 
We tried investigating your provided URL and could not find any problem with the Social9 widget load. Please let us know, additionally if you could provide us with steps to replicate the issue that would help us to investigate it further.

**Comment by jessicaoddi** [comment]
Oh yes! So that's because I put the widget in a div tag and made overflow
hidden so it didn't show the duplicates.

Basically when I placed the CSS tag in the div all those share buttons
showed up twice!



jessica oddi [mobile]

pronounced Jessica Oh-dee
disabled designer [she/her]

email ***@***.***
website JessicaOddi.com
instagram @oddi.jessica

•

For accessibility, I am booking clients in advance throughout the year.
Please check in for available time blocks when requesting work.

Office hours are Tuesday to Friday from 11:00am to 1:00pm and 2:30pm to
6:30pm. Hours may change as I manage PSWs [Personal Support Workers] for
care. I will respond within 1 to 2 business days depending on physical
ability. Thank you for understanding!

**Comment by kunal-saini** [comment]
Hey @jessicaoddi, We have released a patch for the issue, please let us know if it is still occurring for you.

**Comment by jessicaoddi** [comment]
All fixed!

jessica oddi

pronounced Jessica Oh-dee

disabled designer [she/her]

email ***@***.***

website JessicaOddi.com <https://www.jessicaoddi.com/>

instagram @oddi.jessica <https://instagram.com/oddi.jessica>

•

For accessibility, I am booking clients in advance throughout the year.
Please check in for available time blocks when requesting work.

Office hours are Tuesday to Friday from 11:00am to 1:00pm and 2:30 pm to
6:30 pm EST. Hours may change as I manage PSWs [Personal Support Workers]
for care. I will respond within 1 to 2 business days depending on physical
ability. Thank you for understanding!
