### ISSUE TITLE
Can't create new widget

### ISSUE THREAD

**Issue by elenacalvillo** [social9/bug-tracker#2]
![Screen Shot 2021-01-13 at 6 02 06 PM](https://user-images.githubusercontent.com/9559387/104527087-84384600-55c9-11eb-9e8f-b0c1b100cd65.png)

**Comment by kunal-saini** [comment]
Hey @elenacalvillo 

Thanks for bringing this to our attention, it seems like there was downtime, I have escalated this to our engineering team to investigate it further.
Could you please check this now if it works for you?  

thanks!

**Comment by elenacalvillo** [comment]
Hi @kunal-saini ,
Thanks for checking, it worked correctly ~2 days after I reported it. No issues since then.

**Comment by kunal-saini** [comment]
thank you @elenacalvillo 
closing the issue.
