### ISSUE TITLE
Problem to activate Social9

### ISSUE THREAD

**Issue by LouiseSE** [social9/bug-tracker#3]
I'm trying to install social9 on my WP websiste but i can't activate it. When I try to log in in the configuration panel I only get a white screen....

**Comment by soni-kailash** [comment]
Hey @LouiseSE 

Thanks for bringing this to our attention.

I've verified and tested WordPress Plugin and it seems to be working well, could you provide us more detail on it, are you seeing any error while Configuration Sharing interface.

thanks!

**Comment by kunal-saini** [comment]
Hey @LouiseSE 

We will be closing this bug, We have also updated our WordPress plugin and the new version is available out there. Please feel free to re-open this issue or contact us if you need any further assistance.
