### ISSUE TITLE
Sharing icons displayed twice

### ISSUE THREAD

**Issue by the-real-gabriel** [social9/bug-tracker#4]
My pages are loading two instances of the sharing icons. 

I'll be taking this down for now, but here's the html if that helps.

<div class="social-share w-embed"><div class="s9-widget-wrapper"><div id="s9-share-inline" class="s9-share-inline s9-inline"><a title="Facebook" data-provider="Facebook" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-facebook " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
           <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-facebook-1" class="s9-icon s9-icon-facebook" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
              <title id="s9-svg-facebook-1">Facebook</title>
              <g>
                <path d="M22 5.16c-.406-.054-1.806-.16-3.43-.16-3.4 0-5.733 1.825-5.733 5.17v2.882H9v3.913h3.837V27h4.604V16.965h3.823l.587-3.913h-4.41v-2.5c0-1.123.347-1.903 2.198-1.903H22V5.16z" fill-rule="evenodd"></path>
              </g>
						</svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Facebook</span>
					
        </a><a title="Twitter" data-provider="Twitter" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-twitter  " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
						<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-twitter-1" class="s9-icon s9-icon-twitter" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
              <title id="s9-svg-twitter-2">Twitter</title>
             <g>
              <path d="M27.996 10.116c-.81.36-1.68.602-2.592.71a4.526 4.526 0 0 0 1.984-2.496 9.037 9.037 0 0 1-2.866 1.095 4.513 4.513 0 0 0-7.69 4.116 12.81 12.81 0 0 1-9.3-4.715 4.49 4.49 0 0 0-.612 2.27 4.51 4.51 0 0 0 2.008 3.755 4.495 4.495 0 0 1-2.044-.564v.057a4.515 4.515 0 0 0 3.62 4.425 4.52 4.52 0 0 1-2.04.077 4.517 4.517 0 0 0 4.217 3.134 9.055 9.055 0 0 1-5.604 1.93A9.18 9.18 0 0 1 6 23.85a12.773 12.773 0 0 0 6.918 2.027c8.3 0 12.84-6.876 12.84-12.84 0-.195-.005-.39-.014-.583a9.172 9.172 0 0 0 2.252-2.336" fill-rule="evenodd"></path>
            </g>
						</svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Twitter</span>
					
        </a><a title="Email" data-provider="Email" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-email " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
           <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-email-1" class="s9-icon s9-icon-email" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
            <title id="s9-svg-email-1">Email</title>
            <g fill-rule="evenodd"><path d="M27 22.757c0 1.24-.988 2.243-2.19 2.243H7.19C5.98 25 5 23.994 5 22.757V13.67c0-.556.39-.773.855-.496l8.78 5.238c.782.467 1.95.467 2.73 0l8.78-5.238c.472-.28.855-.063.855.495v9.087z"></path><path d="M27 9.243C27 8.006 26.02 7 24.81 7H7.19C5.988 7 5 8.004 5 9.243v.465c0 .554.385 1.232.857 1.514l9.61 5.733c.267.16.8.16 1.067 0l9.61-5.733c.473-.283.856-.96.856-1.514v-.465z"></path></g>
            </svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Email</span>
						
        </a><a title="Pocket" data-provider="Pocket" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-pocket " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
						
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" title="Pocket" alt="Pocket" aria-labelledby="s9-svg-pocket-1" class="s9-icon s9-icon-pocket" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
          <title id="s9-svg-pocket-1">Pocket</title>
          <g>
            <path d="M25.017 7c.554 0 1.023.194 1.407.582.384.388.575.86.575 1.413v6.64c0 1.5-.29 2.932-.87 4.296-.58 1.365-1.358 2.538-2.335 3.518-.976.98-2.144 1.76-3.504 2.335-1.36.575-2.785.863-4.277.863a10.9 10.9 0 0 1-4.292-.863c-1.36-.576-2.53-1.354-3.51-2.335-.98-.98-1.76-2.153-2.34-3.517A10.875 10.875 0 0 1 5 15.635v-6.64c0-.544.196-1.013.588-1.406A1.92 1.92 0 0 1 6.995 7h18.022zm-9.004 13.61c.4 0 .75-.142 1.048-.423l5.17-4.963a1.44 1.44 0 0 0 .472-1.087c0-.418-.147-.774-.44-1.068a1.455 1.455 0 0 0-1.07-.442c-.4 0-.75.14-1.048.422l-4.13 3.965-4.133-3.965a1.465 1.465 0 0 0-1.035-.422c-.418 0-.774.147-1.068.44-.294.295-.44.65-.44 1.07 0 .434.152.796.46 1.086l5.18 4.963c.28.28.626.422 1.036.422z" fill-rule="evenodd"></path>
          </g>
        </svg>

        
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Pocket</span>
					
        </a><a title="LinkedIn" data-provider="LinkedIn" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-linkedin " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
           	<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-linkedin-1" class="s9-icon s9-icon-linkedin" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
              <title id="s9-svg-linkedin-1">LinkedIn</title>
             	<g>
						<path d="M26 25.963h-4.185v-6.55c0-1.56-.027-3.57-2.175-3.57-2.18 0-2.51 1.7-2.51 3.46v6.66h-4.182V12.495h4.012v1.84h.058c.558-1.058 1.924-2.174 3.96-2.174 4.24 0 5.022 2.79 5.022 6.417v7.386zM8.23 10.655a2.426 2.426 0 0 1 0-4.855 2.427 2.427 0 0 1 0 4.855zm-2.098 1.84h4.19v13.468h-4.19V12.495z" fill-rule="evenodd"></path>
						</g>
            </svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">LinkedIn</span>
					
        </a><a title="Facebook" data-provider="Facebook" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-facebook " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
           <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-facebook-1" class="s9-icon s9-icon-facebook" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
              <title id="s9-svg-facebook-1">Facebook</title>
              <g>
                <path d="M22 5.16c-.406-.054-1.806-.16-3.43-.16-3.4 0-5.733 1.825-5.733 5.17v2.882H9v3.913h3.837V27h4.604V16.965h3.823l.587-3.913h-4.41v-2.5c0-1.123.347-1.903 2.198-1.903H22V5.16z" fill-rule="evenodd"></path>
              </g>
						</svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Facebook</span>
					
        </a><a title="Twitter" data-provider="Twitter" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-twitter  " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
						<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-twitter-1" class="s9-icon s9-icon-twitter" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
              <title id="s9-svg-twitter-2">Twitter</title>
             <g>
              <path d="M27.996 10.116c-.81.36-1.68.602-2.592.71a4.526 4.526 0 0 0 1.984-2.496 9.037 9.037 0 0 1-2.866 1.095 4.513 4.513 0 0 0-7.69 4.116 12.81 12.81 0 0 1-9.3-4.715 4.49 4.49 0 0 0-.612 2.27 4.51 4.51 0 0 0 2.008 3.755 4.495 4.495 0 0 1-2.044-.564v.057a4.515 4.515 0 0 0 3.62 4.425 4.52 4.52 0 0 1-2.04.077 4.517 4.517 0 0 0 4.217 3.134 9.055 9.055 0 0 1-5.604 1.93A9.18 9.18 0 0 1 6 23.85a12.773 12.773 0 0 0 6.918 2.027c8.3 0 12.84-6.876 12.84-12.84 0-.195-.005-.39-.014-.583a9.172 9.172 0 0 0 2.252-2.336" fill-rule="evenodd"></path>
            </g>
						</svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Twitter</span>
					
        </a><a title="Email" data-provider="Email" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-email " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
           <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-email-1" class="s9-icon s9-icon-email" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
            <title id="s9-svg-email-1">Email</title>
            <g fill-rule="evenodd"><path d="M27 22.757c0 1.24-.988 2.243-2.19 2.243H7.19C5.98 25 5 23.994 5 22.757V13.67c0-.556.39-.773.855-.496l8.78 5.238c.782.467 1.95.467 2.73 0l8.78-5.238c.472-.28.855-.063.855.495v9.087z"></path><path d="M27 9.243C27 8.006 26.02 7 24.81 7H7.19C5.988 7 5 8.004 5 9.243v.465c0 .554.385 1.232.857 1.514l9.61 5.733c.267.16.8.16 1.067 0l9.61-5.733c.473-.283.856-.96.856-1.514v-.465z"></path></g>
            </svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Email</span>
						
        </a><a title="Pocket" data-provider="Pocket" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-pocket " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
						
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" title="Pocket" alt="Pocket" aria-labelledby="s9-svg-pocket-1" class="s9-icon s9-icon-pocket" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
          <title id="s9-svg-pocket-1">Pocket</title>
          <g>
            <path d="M25.017 7c.554 0 1.023.194 1.407.582.384.388.575.86.575 1.413v6.64c0 1.5-.29 2.932-.87 4.296-.58 1.365-1.358 2.538-2.335 3.518-.976.98-2.144 1.76-3.504 2.335-1.36.575-2.785.863-4.277.863a10.9 10.9 0 0 1-4.292-.863c-1.36-.576-2.53-1.354-3.51-2.335-.98-.98-1.76-2.153-2.34-3.517A10.875 10.875 0 0 1 5 15.635v-6.64c0-.544.196-1.013.588-1.406A1.92 1.92 0 0 1 6.995 7h18.022zm-9.004 13.61c.4 0 .75-.142 1.048-.423l5.17-4.963a1.44 1.44 0 0 0 .472-1.087c0-.418-.147-.774-.44-1.068a1.455 1.455 0 0 0-1.07-.442c-.4 0-.75.14-1.048.422l-4.13 3.965-4.133-3.965a1.465 1.465 0 0 0-1.035-.422c-.418 0-.774.147-1.068.44-.294.295-.44.65-.44 1.07 0 .434.152.796.46 1.086l5.18 4.963c.28.28.626.422 1.036.422z" fill-rule="evenodd"></path>
          </g>
        </svg>

        
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">Pocket</span>
					
        </a><a title="LinkedIn" data-provider="LinkedIn" data-href="https://www.briankrogh.com/learn/how-to-stop-saying-so-um-uh-ah-like-you-know" role="button" tabindex="0" class="s9-btn-share s9-linkedin " style="height: 20px; background-color: transparent; border-radius: 0px;">
          <span class="s9-icon-wrap" style="height: 24px; width: 24px;">
           	<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="s9-svg-linkedin-1" class="s9-icon s9-icon-linkedin" style="height: 24px; width: 24px; fill: rgb(124, 151, 227);">
              <title id="s9-svg-linkedin-1">LinkedIn</title>
             	<g>
						<path d="M26 25.963h-4.185v-6.55c0-1.56-.027-3.57-2.175-3.57-2.18 0-2.51 1.7-2.51 3.46v6.66h-4.182V12.495h4.012v1.84h.058c.558-1.058 1.924-2.174 3.96-2.174 4.24 0 5.022 2.79 5.022 6.417v7.386zM8.23 10.655a2.426 2.426 0 0 1 0-4.855 2.427 2.427 0 0 1 0 4.855zm-2.098 1.84h4.19v13.468h-4.19V12.495z" fill-rule="evenodd"></path>
						</g>
            </svg>
          </span>
					<span class="s9-label" style="font-size: 10.5px; display: none;">LinkedIn</span>
					
        </a></div><div id="s9-share-inline" class="s9-share-inline s9-inline"></div></div></div>

**Comment by kunal-saini** [comment]
Hey @the-real-gabriel 

We will be closing this bug, please feel free to re-open this issue or contact us if you need any further assistance.
