### ISSUE TITLE
Problem in Plugin in Gatsby

### ISSUE THREAD

**Issue by israelavalith** [social9/bug-tracker#5]
The Facebook and Twitter button does not allow sharing, it shows the problem 404. Incusive own your page (social9.com) does not work when sharing on facebook

**Comment by kunal-saini** [comment]
Hey @israelavalith 

Thanks for bringing this to our attention.

I've verified and tested Twitter sharing and it seems to be working well, could you provide us more detail on it, are you seeing any error while sharing with Twitter.

It looks like Facebook is blocking the content posted, we are under investigation to mitigate the issue, we will be updating you on this.

thanks!

**Comment by kunal-saini** [comment]
Hey @israelavalith 

We didn't get any update from Facebook, to resolve the issue we have had switched our shorten sharing domain to ish.re 
this should work fine now. 

thanks, please feel to reopen the issue if you encounter any further problems.
