### ISSUE TITLE
Google lighthouse accessebility score is lower then 100%, because the aria atribute of twitter svg has not a valid value

### ISSUE THREAD

**Issue by Iwankoenderman** [social9/bug-tracker#6]

**Comment by kartiknc** [comment]
Hey @Iwankoenderman, 

We have fixed this issue and updated you on the email. Please let us know in case of any other issues or difficulties.

Thanks,
Kartik

**Comment by kunal-saini** [comment]
Hey @Iwankoenderman 

We are closing this issue, please feel free to re-open this issue or contact us if you need any further assistance.
