### ISSUE TITLE
Gatsby Site Social share not working showing Too big request header

### ISSUE THREAD

**Issue by themeplugs** [social9/bug-tracker#7]

**Comment by kunal-saini** [comment]
Hey @themeplugs , 

Thank you for reporting the issue, could you please provide us with the following more details:

1. Social Provider.
2. Website URL where we can replicate the issue. 

Thanks!

**Comment by kunal-saini** [comment]
Hey @themeplugs 

We have identified an issue with our JS module which leads to this bug, we have already resolved it. We are closing this issue, please feel free to re-open this issue or contact us if you need any further assistance.
