### ISSUE TITLE
FB button invalid by not using percent-encoding in href parameter

### ISSUE THREAD

**Issue by tran62** [social9/bug-tracker#8]
FB share button clicking get error message ( - by not using percent-encoding in href parameter ?)

**Comment by Kuldeep-Chhipa** [comment]
Hey @tran62 

Thank you for reporting the issue, could you please provide us with the following more details:

Website URL where we can replicate the issue.
Thanks!

**Comment by kunal-saini** [comment]
Hey @tran62 

Are you still facing the same issue, please let us know the steps to replicate the issue?

Thanks!

**Comment by tran62** [comment]
thanks,  @kunai-saini 

No more problem now !
